### ISSUE TITLE
AIOTES API stops responding after updating express-gateway_express-gw

### ISSUE THREAD

**Issue by telsaleh** [activage/AIOTES-2.0#2]
Hi, we are following the guidelines in the training platform, and are at the stage after copying the certificates to the certbot container:

"To apply the changes, update the express-gw service (go to “stacks”, select the API stack, then select express-gw service and click “update”)."

When we updated, the service ran but when checking the logs it was stuck at: 

sers.json file not found in / - copying now...
applications.json file not found in / - copying now...
credentials.json file not found in / - copying now...
EXTERNAL_ENDPOINT=https://leedshostname:8081/auth
Waiting for certificates to be available

We have tried updating again, but we got the same issue.

![image](https://user-images.githubusercontent.com/47256078/76111504-4dbc9280-5fd8-11ea-82b3-6a49df799714.png)

![image](https://user-images.githubusercontent.com/47256078/76111515-5319dd00-5fd8-11ea-80b5-82d9c2b22dc7.png)

**Comment by amedranogil** [comment]
could you please share the logs for the express-gateway_certbot service?
it seems there is an issue getting your certificate, ensure you have the DNS entries and Firewall configuration set up.

**Comment by telsaleh** [comment]
We have managed to resolve the issue by removing all stacks, services, containers, volumes, networks relating to AIOTES, with exception for Portainer, then reinstalling.
It would be good to stress in the guide that Portainer should be used as much as possible for any manual configurations, removals, updates, such as copying certificates, if possible, instead of performing these actions via the terminal.
