### ISSUE TITLE
certbot: too many requests for "obtaining a new certificate"

### ISSUE THREAD

**Issue by telsaleh** [activage/AIOTES-2.0#4]
I am unable to connect to AIoTES API. When checking services, I am getting the following error:

```bash
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
An unexpected error occurred:
There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: aiotes.activageleeds.co.uk: see https://letsencrypt.org/docs/rate-limits/
Please see the logfiles in /var/log/letsencrypt for more details.
```
Why is the express_gateway_certbot requesting for a new certificate? I assumed this was done periodically, rather than upon service restart/update

**Comment by amedranogil** [comment]
please sensure the certbot service is using the latest image, this possibility was addressed.
on the mean time please:
1. find the certbot container name, later referred as <certbot>
2. run docker exec <certbot> ls -lhaR /etc/letsencrypt/live/
3. let us know the output (should be save to share)

**Comment by telsaleh** [comment]
Thanks. The issue was resolved by removing all stacks, services, containers, networks, volumes and even images this time, and starting all over again. We also had an Nginx service running, which was brought down, since port 80 is being used by certbot. I would recommend that port numbers that should not be used be highlighted in the guides.
If updates are being made to images, then it would be appropriate to broadcast newer versions (even if minor) to DS platform integrators.
